server:
  port: 8088

spring:
  #  프로필 설정
  server:
    servlet:
      session:
        timeout: 6000

  profiles:
    active: local
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://112.175.17.155:3306/npcc?autoReconnect=true
    username: silk
    password: jbog@2008
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      validation-query: SELECT 1
  jpa:
    hibernate:
      #      절대로 건들지 안됌!!!!
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true

# 쿼리 로깅은 p6spy 사용함 - 라이브시 반영여부는 추후 결정
#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace

# p6spy 설정
decorator.datasource.p6spy:
  enable-logging: true
  multiline: true
  logging: slf4j

#mybatis 설정
mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  mapper-locations: mapper/*.xml
